/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedFindIndexRouteImport } from './routes/_protected/find/index'
import { Route as ProtectedProfileSetupIndexRouteImport } from './routes/_protected/profile/setup/index'
import { Route as ProtectedProfileUserIDIndexRouteImport } from './routes/_protected/profile/$userID/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFindIndexRoute = ProtectedFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileSetupIndexRoute =
  ProtectedProfileSetupIndexRouteImport.update({
    id: '/profile/setup/',
    path: '/profile/setup/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedProfileUserIDIndexRoute =
  ProtectedProfileUserIDIndexRouteImport.update({
    id: '/profile/$userID/',
    path: '/profile/$userID/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/find': typeof ProtectedFindIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/profile/$userID': typeof ProtectedProfileUserIDIndexRoute
  '/profile/setup': typeof ProtectedProfileSetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/find': typeof ProtectedFindIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/profile/$userID': typeof ProtectedProfileUserIDIndexRoute
  '/profile/setup': typeof ProtectedProfileSetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/find/': typeof ProtectedFindIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/profile/$userID/': typeof ProtectedProfileUserIDIndexRoute
  '/_protected/profile/setup/': typeof ProtectedProfileSetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/find'
    | '/profile'
    | '/profile/$userID'
    | '/profile/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/find'
    | '/profile'
    | '/profile/$userID'
    | '/profile/setup'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/find/'
    | '/_protected/profile/'
    | '/_protected/profile/$userID/'
    | '/_protected/profile/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/find/': {
      id: '/_protected/find/'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof ProtectedFindIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile/setup/': {
      id: '/_protected/profile/setup/'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProtectedProfileSetupIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile/$userID/': {
      id: '/_protected/profile/$userID/'
      path: '/profile/$userID'
      fullPath: '/profile/$userID'
      preLoaderRoute: typeof ProtectedProfileUserIDIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedFindIndexRoute: typeof ProtectedFindIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedProfileUserIDIndexRoute: typeof ProtectedProfileUserIDIndexRoute
  ProtectedProfileSetupIndexRoute: typeof ProtectedProfileSetupIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedFindIndexRoute: ProtectedFindIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedProfileUserIDIndexRoute: ProtectedProfileUserIDIndexRoute,
  ProtectedProfileSetupIndexRoute: ProtectedProfileSetupIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
